language : generic
sudo : required
services:
  - docker

before_install:
  - docker build -t abhishek1705/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhishek1705/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker-1"
  env: "Docker1-env"
  bucket_name: "elasticbeanstalk-ap-south-1-217332117450"
  bucket_path: "Docker-1"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"